"""
Email Service for sending newsletters
"""

import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Optional
from dotenv import load_dotenv

load_dotenv()

class EmailService:
    def __init__(self):
        self.smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
        self.smtp_port = int(os.getenv("SMTP_PORT", "587"))
        self.smtp_username = os.getenv("SMTP_USERNAME")
        self.smtp_password = os.getenv("SMTP_PASSWORD")
        self.from_email = os.getenv("FROM_EMAIL", self.smtp_username)
        self.from_name = os.getenv("FROM_NAME", "Devbrah")
    
    def is_configured(self) -> bool:
        """Check if email is configured"""
        return bool(self.smtp_username and self.smtp_password)
    
    async def send_newsletter(
        self,
        to_email: str,
        to_name: str,
        subject: str,
        html_content: str
    ) -> bool:
        """Send newsletter email"""
        if not self.is_configured():
            print(f"⚠️ Email not configured. Would send to {to_email}")
            print(f"Subject: {subject}")
            return False
        
        try:
            # Create message
            msg = MIMEMultipart('alternative')
            msg['Subject'] = subject
            msg['From'] = f"{self.from_name} <{self.from_email}>"
            msg['To'] = to_email
            
            # Create plain text version
            text_content = f"""
🚀 Devbrah Weekly Newsletter

Hello {to_name}!

Your personalized career growth newsletter is ready.

View the full newsletter in your browser or check the HTML version.

Generated by Devbrah | Microsoft for Startups Track
"""
            
            # Attach parts
            part1 = MIMEText(text_content, 'plain')
            part2 = MIMEText(html_content, 'html')
            
            msg.attach(part1)
            msg.attach(part2)
            
            # Send email
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.smtp_username, self.smtp_password)
                server.send_message(msg)
            
            print(f"✅ Newsletter sent successfully to {to_email}")
            return True
        
        except Exception as e:
            print(f"❌ Failed to send email to {to_email}: {str(e)}")
            return False
    
    async def send_test_email(self, to_email: str) -> bool:
        """Send a test email"""
        return await self.send_newsletter(
            to_email=to_email,
            to_name="Test User",
            subject="Test Email from Devbrah",
            html_content="<h1>Test Email</h1><p>This is a test email from Devbrah.</p>"
        )

